import type { DatapathLayout } from
  "../core/types";

import {
  SINGLE_CYCLE_COMPONENT as C,
  SINGLE_CYCLE_WIRE as W,
  type SingleCycleComponentId,
  type SingleCycleWireId,
} from "./singleCycleIds";

/**
 * Single-cycle layout whose component-connected wire endpoints are resolved
 * from named ports. The route arrays now contain intermediate bends only.
 */
export const SINGLE_CYCLE_LAYOUT:
  DatapathLayout<
    SingleCycleComponentId,
    SingleCycleWireId
  > = {
    viewBox: {
      width: 1600,
      height: 1000,
    },

    components: [
      {
        id: C.pc,
        label: "PC",
        shape: "block",
        x: 40,
        y: 400,
        width: 55,
        height: 120,
        ports: [
          { id: "input", label: "", side: "left", position: 70 / 120 },
          { id: "output", label: "", side: "right", position: 30 / 120 },
        ],
      },
      {
        id: C.instructionMemory,
        label: "Instr. Mem",
        shape: "block",
        x: 135,
        y: 355,
        width: 130,
        height: 200,
        ports: [
          { id: "read-address", label: "Read address", side: "left", position: 75 / 200 },
          { id: "instruction", label: "Instr[31-0]", side: "right", position: 130 / 200 },
        ],
      },
      {
        id: C.pcPlusFourAdder,
        label: "Add",
        shape: "adder",
        x: 185,
        y: 80,
        width: 40,
        height: 80,
        ports: [
          { id: "input-a", label: "", side: "left", position: 20 / 80 },
          { id: "input-b", label: "", side: "left", position: 65 / 80 },
          { id: "result", label: "", side: "right", position: 40 / 80 },
        ],
      },
      {
        id: C.jumpShiftLeftTwo,
        label: "Shift",
        subtitle: "left 2",
        shape: "ellipse",
        x: 480,
        y: 40,
        width: 60,
        height: 60,
        ports: [
          { id: "input", label: "", side: "left", position: 35 / 60 },
          { id: "output", label: "", side: "right", position: 35 / 60 },
        ],
      },
      {
        id: C.controlUnit,
        label: "Control",
        shape: "ellipse",
        x: 460,
        y: 165,
        width: 125,
        height: 195,
        ports: [
          { id: "instruction", label: "Opcode [5-0]", side: "left", position: 118 / 195 },
          { id: "jump", label: "", side: "right", position: 60 / 195, anchorOffset: { x: -12, y: 0 } },
          { id: "branch", label: "", side: "right", position: 80 / 195, anchorOffset: { x: -5, y: 0 } },
          { id: "memory-read", label: "", side: "right", position: 100 / 195, anchorOffset: { x: -1, y: 0 } },
          { id: "mem-to-reg", label: "", side: "right", position: 120 / 195 },
          { id: "alu-op", label: "", side: "right", position: 140 / 195, anchorOffset: { x: -2, y: 0 } },
          { id: "memory-write", label: "", side: "right", position: 160 / 195, anchorOffset: { x: -6, y: 0 } },
          { id: "alu-src", label: "", side: "right", position: 180 / 195, anchorOffset: { x: -14, y: 0 } },
          { id: "reg-dst", label: "", side: "bottom", position: 40 / 125, anchorOffset: { x: 0, y: 5 } },
          { id: "register-write", label: "", side: "bottom", position: 70 / 125, anchorOffset: { x: 0, y: 5 } },
        ],
      },
      {
        id: C.regDstMux,
        label: "Mux",
        shape: "mux",
        x: 450,
        y: 500,
        width: 45,
        height: 100,
        ports: [
          { id: "rt-input", label: "0", side: "left", position: 25 / 100 },
          { id: "rd-input", label: "1", side: "left", position: 75 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100 },
          { id: "select", label: "", side: "top", position: 23 / 45 },
        ],
      },
      {
        id: C.registerFile,
        label: "Register File",
        shape: "block",
        x: 530,
        y: 400,
        width: 160,
        height: 250,
        ports: [
          { id: "read-register-1", label: "Read reg. 1", side: "left", position: 40 / 250 },
          { id: "read-register-2", label: "Read reg. 2", side: "left", position: 65 / 250 },
          { id: "write-register", label: "Write reg.", side: "left", position: 150 / 250 },
          { id: "write-data", label: "Write data", side: "left", position: 220 / 250 },
          { id: "read-data-1", label: "Read data 1", side: "right", position: 85 / 250 },
          { id: "read-data-2", label: "Read data 2", side: "right", position: 175 / 250 },
          { id: "register-write", label: "", side: "top", position: 95 / 160, anchorOffset: { x: 0, y: 20 } },
        ],
      },
      {
        id: C.signExtension,
        label: "Sign Ext.",
        shape: "ellipse",
        x: 550,
        y: 760,
        width: 120,
        height: 90,
        ports: [
          { id: "input", label: "", side: "left", position: 45 / 90 },
          { id: "output", label: "", side: "right", position: 45 / 90 },
        ],
      },
      {
        id: C.aluControl,
        label: "ALU",
        shape: "ellipse",
        x: 795,
        y: 760,
        width: 120,
        height: 105,
        ports: [
          { id: "alu-op-input", label: "", side: "left", position: 30 / 105 },
          { id: "funct-input", label: "Funct [6-0]", inset: 14, side: "bottom", position: 55 / 120 },
          { id: "output", label: "", side: "top", position: 60 / 120 },
        ],
      },
      {
        id: C.aluSrcMux,
        label: "Mux",
        shape: "mux",
        x: 775,
        y: 570,
        width: 45,
        height: 100,
        ports: [
          { id: "register-input", label: "0", side: "left", position: 25 / 100 },
          { id: "immediate-input", label: "1", side: "left", position: 75 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100 },
          { id: "select", label: "", side: "top", position: 23 / 45 },
        ],
      },
      {
        id: C.alu,
        label: "ALU",
        shape: "alu",
        x: 850,
        y: 470,
        width: 100,
        height: 130,
        ports: [
          { id: "source-a", label: "SrcA", side: "left", position: 35 / 130 },
          { id: "source-b", label: "SrcB", side: "left", position: 105 / 130 },
          { id: "zero", label: "Zero", side: "right", position: 50 / 130, anchorOffset: { x: 5, y: 0 } },
          { id: "result", label: "Result", side: "right", position: 78 / 130, anchorOffset: { x: 5, y: 0 } },
          { id: "control", label: "", side: "bottom", position: 60 / 100, anchorOffset: { x: 0, y: -20 } },
        ],
      },
      {
        id: C.branchShiftLeftTwo,
        label: "Shift",
        subtitle: "left 2",
        shape: "ellipse",
        x: 750,
        y: 180,
        width: 60,
        height: 60,
        ports: [
          { id: "input", label: "", side: "left", position: 30 / 60 },
          { id: "output", label: "", side: "right", position: 30 / 60 },
        ],
      },
      {
        id: C.branchTargetAdder,
        label: "Add",
        shape: "adder",
        x: 885,
        y: 145,
        width: 40,
        height: 80,
        ports: [
          { id: "input-a", label: "", side: "left", position: 25 / 80 },
          { id: "input-b", label: "", side: "left", position: 65 / 80 },
          { id: "result", label: "", side: "right", position: 40 / 80, anchorOffset: { x: 5, y: 0 } },
        ],
      },
      {
        id: C.branchAndGate,
        label: "",
        shape: "and-gate",
        x: 990,
        y: 200,
        width: 50,
        height: 50,
        ports: [
          { id: "branch-input", label: "", side: "left", position: 15 / 50 },
          { id: "zero-input", label: "", side: "left", position: 35 / 50, anchorOffset: { x: 10, y: 0 } },
          { id: "output", label: "", side: "right", position: 25 / 50, anchorOffset: { x: -40, y: 0 } },
        ],
      },
      {
        id: C.dataMemory,
        label: "Data",
        shape: "block",
        x: 1000,
        y: 445,
        width: 145,
        height: 175,
        ports: [
          { id: "address", label: "Address", side: "left", position: 103 / 175 },
          { id: "write-data", label: "Write data", side: "bottom", position: 50 / 145, anchorOffset: { x: 0, y: 5 } },
          { id: "read-data", label: "Read data", side: "right", position: 130 / 175, anchorOffset: { x: -45, y: 0 } },
          { id: "memory-read", label: "", side: "bottom", position: 100 / 145 },
          { id: "memory-write", label: "", side: "top", position: 75 / 145, anchorOffset: { x: 0, y: 5 } },
        ],
      },
      {
        id: C.memToRegMux,
        label: "Mux",
        shape: "mux",
        x: 1200,
        y: 550,
        width: 45,
        height: 100,
        ports: [
          { id: "memory-input", label: "1", side: "left", position: 25 / 100 },
          { id: "alu-input", label: "0", side: "left", position: 85 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100 },
          { id: "select", label: "", side: "top", position: 20 / 45 },
        ],
      },
      {
        id: C.pcSrcMux,
        label: "Mux",
        shape: "mux",
        x: 1125,
        y: 110,
        width: 45,
        height: 100,
        ports: [
          { id: "sequential-input", label: "0", side: "left", position: 30 / 100, anchorOffset: { x: -5, y: 0 } },
          { id: "branch-input", label: "1", side: "left", position: 75 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100, anchorOffset: { x: -5, y: 0 } },
          { id: "select", label: "", side: "bottom", position: 25 / 45, anchorOffset: { x: 0, y: -5 } },
        ],
      },
      {
        id: C.jumpMux,
        label: "Mux",
        shape: "mux",
        x: 1200,
        y: 75,
        width: 45,
        height: 100,
        ports: [
          { id: "jump-input", label: "1", side: "left", position: 25 / 100 },
          { id: "sequential-input", label: "0", side: "left", position: 85 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100 },
          { id: "select", label: "", side: "top", position: 10 / 45 },
        ],
      },
    ],
    wires: [
      {
        id: W.pcToInstructionMemory,
        kind: "pc",
        from: port(C.pc, "output"),
        to: port(C.instructionMemory, "read-address"),
      },
      {
        id: W.pcToPcPlusFourAdder,
        kind: "pc",
        from: port(C.pc, "output"),
        to: port(C.pcPlusFourAdder, "input-a"),
        route: [
          { x: 110, y: 430 },
          { x: 110, y: 100 },
        ],
      },
      {
        id: W.constantFourToPcPlusFourAdder,
        kind: "data",
        label: "+ 4",
        from: point(145, 145),
        to: port(C.pcPlusFourAdder, "input-b"),
      },
      {
        id: W.pcPlusFourToBranchTargetAdder,
        kind: "pc",
        label: "PC + 4 [31-0]",
        labelAt: 0.81,
        from: port(C.pcPlusFourAdder, "result"),
        to: port(C.branchTargetAdder, "input-a"),
        route: [
          { x: 250, y: 120 },
          { x: 250, y: 140 },
          { x: 700, y: 140 },
          { x: 700, y: 170 },
        ],
      },
      {
        id: W.pcPlusFourToPcSrcMux,
        kind: "pc",
        label: "PC + 4 [31-0]",
        labelAt: 0.59,
        from: port(C.pcPlusFourAdder, "result"),
        to: port(C.pcSrcMux, "sequential-input"),
        route: [
          { x: 250, y: 120 },
          { x: 250, y: 140 },
        ],
      },
      {
        id: W.instructionToControlUnit,
        kind: "data",
        label: "Instruction [31-26]",
        labelAt: 0.75,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.controlUnit, "instruction"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 283 },
        ],
      },
      {
        id: W.instructionRsToRegisterFile,
        kind: "data",
        label: "Instruction [25-21]",
        labelAt: 0.45,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.registerFile, "read-register-1"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 440 },
        ],
      },
      {
        id: W.instructionRtToRegisterFile,
        kind: "data",
        label: "Instruction [20-16]",
        labelAt: 0.40,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.registerFile, "read-register-2"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 465 },
        ],
      },
      {
        id: W.instructionRtToRegDstMux,
        kind: "data",
        from: port(C.instructionMemory, "instruction"),
        to: port(C.regDstMux, "rt-input"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 465 },
          { x: 410, y: 465 },
          { x: 410, y: 525 },
        ],
      },
      {
        id: W.instructionRdToRegDstMux,
        kind: "data",
        label: "Instruction [15-11]",
        labelAt: 0.68,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.regDstMux, "rd-input"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 575 },
        ],
      },
      {
        id: W.instructionImmediateToSignExtension,
        kind: "data",
        label: "Instruction [15-0]",
        labelAt: 0.69,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.signExtension, "input"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 805 },
        ],
      },
      {
        id: W.instructionFunctToAluControl,
        kind: "data",
        label: "Instruction [5-0]",
        labelAt: 0.75,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.aluControl, "funct-input"),
        route: [
          { x: 285, y: 485 },
          { x: 285, y: 805 },
          { x: 475, y: 805 },
          { x: 475, y: 890 },
          { x: 850, y: 890 },
        ],
      },
      {
        id: W.instructionJumpFieldToJumpShift,
        kind: "data",
        label: "Instruction [25-0]",
        labelAt: 0.80,
        from: port(C.instructionMemory, "instruction"),
        to: port(C.jumpShiftLeftTwo, "input"),
        route: [
          { x: 275, y: 485 },
          { x: 275, y: 75 },
        ],
      },
      {
        id: W.regDstMuxToRegisterWriteAddress,
        kind: "data",
        from: port(C.regDstMux, "output"),
        to: port(C.registerFile, "write-register"),
      },
      {
        id: W.jumpShiftToJumpMux1,
        kind: "pc",
        label: "Jump address [27-0]",
        labelAt: 0.26,
        from: port(C.jumpShiftLeftTwo, "output"),
        to: point(800, 75),
      },
      {
        id: W.jumpShiftToJumpMux2,
        kind: "pc",
        label: "Jump address [31-0]",
        labelAt: 0.20,
        from: point(800, 75),
        to: port(C.jumpMux, "jump-input"),
        route: [
          { x: 1150, y: 75 },
          { x: 1150, y: 100 },
        ],
      },
      {
        id: W.pcHighBitsToJumpMux,
        kind: "pc",
        label: "PC + 4 [31-28]",
        labelAt: 0.86,
        from: port(C.pcPlusFourAdder, "result"),
        to: point(800, 75),
        route: [
          { x: 250, y: 120 },
          { x: 250, y: 140 },
          { x: 700, y: 140 },
          { x: 700, y: 115 },
          { x: 800, y: 115 },
        ],
      },
      {
        id: W.controlToRegDstMux,
        kind: "control",
        label: "RegDst",
        labelAt: 0.25,
        from: port(C.controlUnit, "reg-dst"),
        to: port(C.regDstMux, "select"),
        route: [
          { x: 473, y: 400 },
        ],
      },
      {
        id: W.controlToJumpMux,
        kind: "control",
        label: "Jump",
        labelAt: 0.05,
        from: port(C.controlUnit, "jump"),
        to: port(C.jumpMux, "select"),
        route: [
          { x: 685, y: 225 },
          { x: 685, y: 50 },
          { x: 1210, y: 50 },
        ],
      },
      {
        id: W.controlToBranchAndGate,
        kind: "control",
        label: "Branch",
        labelAt: 0.10,
        from: port(C.controlUnit, "branch"),
        to: port(C.branchAndGate, "branch-input"),
        route: [
          { x: 945, y: 245 },
          { x: 945, y: 215 },
        ],
      },
      {
        id: W.controlToMemoryRead,
        kind: "control",
        label: "MemRead",
        labelAt: 0.025,
        from: port(C.controlUnit, "memory-read"),
        to: port(C.dataMemory, "memory-read"),
        route: [
          { x: 1275, y: 265 },
          { x: 1275, y: 800 },
          { x: 1100, y: 800 },
        ],
      },
      {
        id: W.controlToMemToRegMux,
        kind: "control",
        label: "MemToReg",
        labelAt: 0.05,
        from: port(C.controlUnit, "mem-to-reg"),
        to: port(C.memToRegMux, "select"),
        route: [
          { x: 1220, y: 285 },
        ],
      },
      {
        id: W.controlToAluControl,
        kind: "control",
        label: "ALUOp",
        labelAt: 0.05,
        from: port(C.controlUnit, "alu-op"),
        to: port(C.aluControl, "alu-op-input"),
        route: [
          { x: 700, y: 305 },
          { x: 700, y: 790 },
        ],
      },
      {
        id: W.controlToMemoryWrite,
        kind: "control",
        label: "MemWrite",
        labelAt: 0.05,
        from: port(C.controlUnit, "memory-write"),
        to: port(C.dataMemory, "memory-write"),
        route: [
          { x: 1075, y: 325 },
        ],
      },
      {
        id: W.controlToAluSrcMux,
        kind: "control",
        label: "ALUSrc",
        labelAt: 0.05,
        from: port(C.controlUnit, "alu-src"),
        to: port(C.aluSrcMux, "select"),
        route: [
          { x: 740, y: 345 },
          { x: 740, y: 550 },
          { x: 798, y: 550 },
        ],
      },
      {
        id: W.controlToRegisterWrite,
        kind: "control",
        label: "RegWrite",
        labelAt: 0.35,
        from: port(C.controlUnit, "register-write"),
        to: port(C.registerFile, "register-write"),
        route: [
          { x: 530, y: 375 },
          { x: 625, y: 375 },
        ],
      },
      {
        id: W.registerReadDataOneToAlu,
        kind: "data",
        from: port(C.registerFile, "read-data-1"),
        to: port(C.alu, "source-a"),
        route: [
          { x: 810, y: 485 },
          { x: 810, y: 505 },
        ],
      },
      {
        id: W.registerReadDataTwoToAluSrcMux,
        kind: "data",
        from: port(C.registerFile, "read-data-2"),
        to: port(C.aluSrcMux, "register-input"),
        route: [
          { x: 750, y: 575 },
          { x: 750, y: 595 },
        ],
      },
      {
        id: W.registerReadDataTwoToDataMemory,
        kind: "memory",
        from: port(C.registerFile, "read-data-2"),
        to: port(C.dataMemory, "write-data"),
        route: [
          { x: 720, y: 575 },
          { x: 720, y: 690 },
          { x: 1050, y: 690 },
        ],
      },
      {
        id: W.signExtensionToAluSrcMux,
        kind: "data",
        from: port(C.signExtension, "output"),
        to: port(C.aluSrcMux, "immediate-input"),
        route: [
          { x: 730, y: 805 },
          { x: 730, y: 645 },
        ],
      },
      {
        id: W.signExtensionToBranchShift,
        kind: "branch",
        from: port(C.signExtension, "output"),
        to: port(C.branchShiftLeftTwo, "input"),
        route: [
          { x: 730, y: 805 },
          { x: 730, y: 210 },
        ],
      },
      {
        id: W.branchShiftToBranchTargetAdder,
        kind: "branch",
        from: port(C.branchShiftLeftTwo, "output"),
        to: port(C.branchTargetAdder, "input-b"),
      },
      {
        id: W.aluSrcMuxToAlu,
        kind: "data",
        from: port(C.aluSrcMux, "output"),
        to: port(C.alu, "source-b"),
        route: [
          { x: 835, y: 620 },
          { x: 835, y: 575 },
        ],
      },
      {
        id: W.aluControlToAlu,
        kind: "control",
        from: port(C.aluControl, "output"),
        to: port(C.alu, "control"),
        route: [
          { x: 855, y: 720 },
          { x: 910, y: 720 },
        ],
      },
      {
        id: W.aluZeroToBranchAndGate,
        kind: "control",
        labelAt: 0.05,
        from: port(C.alu, "zero"),
        to: port(C.branchAndGate, "zero-input"),
        route: [
          { x: 980, y: 520 },
          { x: 980, y: 235 },
        ],
      },
      {
        id: W.aluResultToDataMemory,
        kind: "memory",
        from: port(C.alu, "result"),
        to: port(C.dataMemory, "address"),
      },
      {
        id: W.aluResultToMemToRegMux,
        kind: "data",
        from: port(C.alu, "result"),
        to: port(C.memToRegMux, "alu-input"),
        route: [
          { x: 965, y: 548 },
          { x: 965, y: 635 },
        ],
      },
      {
        id: W.dataMemoryToMemToRegMux,
        kind: "memory",
        from: port(C.dataMemory, "read-data"),
        to: port(C.memToRegMux, "memory-input"),
      },
      {
        id: W.memToRegMuxToRegisterWriteData,
        kind: "data",
        from: port(C.memToRegMux, "output"),
        to: port(C.registerFile, "write-data"),
        route: [
          { x: 1260, y: 600 },
          { x: 1260, y: 900 },
          { x: 500, y: 900 },
          { x: 500, y: 620 },
        ],
      },
      {
        id: W.branchTargetAdderToPcSrcMux,
        kind: "branch",
        from: port(C.branchTargetAdder, "result"),
        to: port(C.pcSrcMux, "branch-input"),
      },
      {
        id: W.branchAndGateToPcSrcMux,
        kind: "control",
        from: port(C.branchAndGate, "output"),
        to: port(C.pcSrcMux, "select"),
        route: [
          { x: 1150, y: 225 },
        ],
      },
      {
        id: W.pcSrcMuxToJumpMux,
        kind: "pc",
        from: port(C.pcSrcMux, "output"),
        to: port(C.jumpMux, "sequential-input"),
      },
      {
        id: W.jumpMuxToPc,
        kind: "pc",
        from: port(C.jumpMux, "output"),
        to: port(C.pc, "input"),
        route: [
          { x: 1260, y: 125 },
          { x: 1260, y: 30 },
          { x: 20, y: 30 },
          { x: 20, y: 470 },
        ],
      },
    ],
  };

function port(
  componentId: SingleCycleComponentId,
  portId: string,
) {
  return { componentId, portId } as const;
}

function point(x: number, y: number) {
  return { point: { x, y } } as const;
}
