import type { DatapathLayout } from
  "../core/types";

import {
  MULTI_CYCLE_COMPONENT as C,
  MULTI_CYCLE_WIRE as W,
  type MultiCycleComponentId,
  type MultiCycleWireId,
} from "./multiCycleIds";

/**
 * Multicycle layout using named component-port wire anchors.
 * Route arrays contain intermediate bends only.
 */
export const MULTI_CYCLE_LAYOUT:
  DatapathLayout<
    MultiCycleComponentId,
    MultiCycleWireId
  > = {
    viewBox: {
      width: 1600,
      height: 1000,
    },

    components: [
      {
        id: C.pc,
        label: "PC",
        shape: "block",
        x: 30,
        y: 420,
        width: 55,
        height: 110,
        ports: [
          { id: "output", label: "", side: "right", position: 15 / 110 },
          { id: "input", label: "", side: "left", position: 80 / 110 },
          { id: "enable", label: "", side: "top", position: 25 / 55 },
        ],
      },
      {
        id: C.pcEnableGate,
        label: "PC Enable",
        shape: "or-gate",
        orientation: "left",
        x: 85,
        y: 60,
        width: 120,
        height: 65,
        ports: [
          {
            id: "unconditional-input",
            label: "",
            side: "right",
            position: 51.5 / 65,
          },
          {
            id: "conditional-input",
            label: "",
            side: "right",
            position: 15.5 / 65,
          },
          {
            id: "output",
            label: "",
            side: "left",
            position: 0.5,
          },
        ],
      },
      {
        id: C.branchAndGate,
        label: "AND",
        shape: "and-gate",
        orientation: "left",
        x: 260,
        y: 50,
        width: 60,
        height: 50,
        ports: [
          {
            id: "pc-write-cond-input",
            label: "",
            side: "right",
            position: 38.5 / 55,
          },
          {
            id: "zero-input",
            label: "Zero",
            side: "right",
            position: 10 / 55,
          },
          {
            id: "output",
            label: "",
            side: "left",
            position: 0.5,
          },
        ],
      },
      {
        id: C.iorDMux,
        label: "Mux",
        shape: "mux",
        x: 125,
        y: 405,
        width: 45,
        height: 110,
        ports: [
          { id: "pc-input", label: "0", side: "left", position: 30 / 110 },
          { id: "alu-out-input", label: "1", side: "left", position: 85 / 110 },
          { id: "output", label: "", side: "right", position: 55 / 110 },
          { id: "select", label: "", side: "top", position: 20 / 45 },
        ],
      },
      {
        id: C.memory,
        label: "Memory",
        shape: "block",
        x: 215,
        y: 425,
        width: 155,
        height: 245,
        ports: [
          { id: "address", label: "Address", side: "left", position: 35 / 245 },
          { id: "write-data", label: "Write data", side: "left", position: 190 / 245 },
          { id: "data-output", label: "MemData", side: "right", position: 25 / 245 },
          { id: "memory-read", label: "", side: "top", position: 75 / 155 },
          { id: "memory-write", label: "", side: "top", position: 110 / 155 },
        ],
      },
      {
        id: C.instructionRegister,
        label: "IR",
        subtitle: "Instr. Register",
        shape: "block",
        x: 420,
        y: 300,
        width: 120,
        height: 300,
        ports: [
          { id: "input", label: "", side: "left", position: 45 / 90 },
          { id: "output", label: "", side: "right", position: 45 / 90 },
          { id: "write-enable", label: "", side: "top", position: 50 / 120 },
        ],
      },
      {
        id: C.memoryDataRegister,
        label: "MDR",
        subtitle: "Mem. Data Reg",
        shape: "block",
        x: 420,
        y: 700,
        width: 120,
        height: 90,
        ports: [
          { id: "input", label: "", side: "left", position: 45 / 90 },
          { id: "output", label: "", side: "right", position: 45 / 90 },
        ],
      },
      {
        id: C.controlUnit,
        label: "Control",
        shape: "ellipse",
        x: 650,
        y: 55,
        width: 100,
        height: 205,
        ports: [
          { id: "instruction", label: "Opcode [5:0]", inset: 29, side: "bottom", position: 80 / 160,},
          { id: "pc-write-cond", label: "", side: "left", position: 30 / 205 },
          { id: "pc-write", label: "", side: "left", position: 55 / 205 },
          { id: "ior-d", label: "", side: "left", position: 80 / 205 },
          { id: "memory-read", label: "", side: "left", position: 105 / 205 },
          { id: "memory-write", label: "", side: "left", position: 130 / 205 },
          { id: "mem-to-reg", label: "", side: "left", position: 155 / 205 },
          { id: "ir-write", label: "", side: "left", position: 180 / 205 },
          { id: "reg-dst", label: "", side: "right", position: 205 / 205 },
          { id: "pc-source", label: "", side: "right", position: 30 / 205 },
          { id: "alu-op", label: "", side: "right", position: 60 / 205 },
          { id: "alu-src-a", label: "", side: "right", position: 90 / 205 },
          { id: "alu-src-b", label: "", side: "right", position: 120 / 205 },
          { id: "register-write", label: "", side: "right", position: 150 / 205 },
        ],
      },
      {
        id: C.regDstMux,
        label: "Mux",
        shape: "mux",
        x: 625,
        y: 465,
        width: 45,
        height: 100,
        ports: [
          { id: "rt-input", label: "0", side: "left", position: 25 / 100 },
          { id: "rd-input", label: "1", side: "left", position: 75 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100 },
          { id: "select", label: "", side: "top", position: 15 / 45 },
        ],
      },
      {
        id: C.memToRegMux,
        label: "Mux",
        shape: "mux",
        x: 635,
        y: 600,
        width: 45,
        height: 100,
        ports: [
          { id: "alu-out-input", label: "0", side: "left", position: 25 / 100 },
          { id: "mdr-input", label: "1", side: "left", position: 75 / 100 },
          { id: "output", label: "", side: "right", position: 50 / 100 },
          { id: "select", label: "", side: "top", position: 20 / 45 },
        ],
      },
      {
        id: C.registerFile,
        label: "Register File",
        shape: "block",
        x: 720,
        y: 335,
        width: 150,
        height: 300,
        ports: [
          { id: "read-register-1", label: "Read reg. 1", side: "left", position: 55 / 300 },
          { id: "read-register-2", label: "Read reg. 2", side: "left", position: 90 / 300 },
          { id: "write-register", label: "Write reg.", side: "left", position: 165 / 300 },
          { id: "write-data", label: "Write data", side: "left", position: 235 / 300 },
          { id: "read-data-1", label: "Read data 1", side: "right", position: 88 / 300 },
          { id: "read-data-2", label: "Read data 2", side: "right", position: 195 / 300 },
          { id: "register-write", label: "", side: "top", position: 145 / 175 },
        ],
      },
      {
        id: C.aRegister,
        label: "A",
        shape: "block",
        x: 900,
        y: 395,
        width: 50,
        height: 50,
        ports: [
          { id: "input", label: "", side: "left", position: 50 / 90 },
          { id: "output", label: "", side: "right", position: 45 / 90 },
        ],
      },
      {
        id: C.bRegister,
        label: "B",
        shape: "block",
        x: 900,
        y: 505,
        width: 50,
        height: 50,
        ports: [
          { id: "input", label: "", side: "left", position: 45 / 90 },
          { id: "output", label: "", side: "right", position: 45 / 90 },
        ],
      },
      {
        id: C.signExtension,
        label: "Sign Ext.",
        shape: "ellipse",
        x: 740,
        y: 735,
        width: 85,
        height: 85,
        ports: [
          { id: "input", label: "", side: "left", position: 40 / 85 },
          { id: "output", label: "", side: "right", position: 40 / 85 },
        ],
      },
      {
        id: C.branchShiftLeftTwo,
        label: "Shift",
        subtitle: "left 2",
        shape: "ellipse",
        x: 880,
        y: 747,
        width: 60,
        height: 60,
        ports: [
          { id: "input", label: "", side: "left", position: 35 / 75 },
          { id: "output", label: "", side: "right", position: 35 / 75 },
        ],
      },
      {
        id: C.aluSourceAMux,
        label: "Mux",
        shape: "mux",
        x: 1000,
        y: 335,
        width: 45,
        height: 110,
        ports: [
          { id: "pc-input", label: "0", side: "left", position: 30 / 110 },
          { id: "a-input", label: "1", side: "left", position: 85 / 110 },
          { id: "output", label: "", side: "right", position: 55 / 110 },
          { id: "select", label: "", side: "top", position: 22 / 45 },
        ],
      },
      {
        id: C.aluSourceBMux,
        label: "Mux",
        shape: "mux",
        x: 1000,
        y: 508,
        width: 45,
        height: 170,
        ports: [
          { id: "b-input", label: "0", side: "left", position: 22 / 170 },
          { id: "four-input", label: "1", side: "left", position: 65 / 170 },
          { id: "immediate-input", label: "2", side: "left", position: 110 / 170 },
          { id: "shifted-input", label: "3", side: "left", position: 145 / 170 },
          { id: "output", label: "", side: "right", position: 85 / 170 },
          { id: "select", label: "", side: "top", position: 22 / 45 },
        ],
      },
      {
        id: C.alu,
        label: "ALU",
        shape: "alu",
        x: 1090,
        y: 380,
        width: 120,
        height: 180,
        ports: [
          { id: "source-a", label: "SrcA", side: "left", position: 45 / 180 },
          { id: "source-b", label: "SrcB", side: "left", position: 140 / 180 },
          { id: "zero", label: "Zero", side: "right", position: 65 / 180 },
          { id: "result", label: "Result", side: "right", position: 115 / 180 },
          { id: "control", label: "", side: "bottom", position: 60 / 120, anchorOffset: { x: 0, y: -25 } },
        ],
      },
      {
        id: C.aluControl,
        label: "ALU Control",
        shape: "ellipse",
        x: 1015,
        y: 685,
        width: 125,
        height: 95,
        ports: [
          { id: "alu-op-input", label: "ALUOp", side: "right", position: 30 / 95 },
          { id: "funct-input", label: "Funct", side: "bottom", position: 60 / 125 },
          { id: "output", label: "", side: "top", position: 60 / 125 },
        ],
      },
      {
        id: C.aluOutRegister,
        label: "ALUOut",
        shape: "block",
        x: 1250,
        y: 453,
        width: 75,
        height: 80,
        ports: [
          { id: "input", label: "", side: "left", position: 50 / 95 },
          { id: "output", label: "", side: "right", position: 50 / 95 },
        ],
      },
      {
        id: C.jumpShiftLeftTwo,
        label: "Shift",
        subtitle: "left 2",
        shape: "ellipse",
        x: 1050,
        y: 250,
        width: 80,
        height: 75,
        ports: [
          { id: "input", label: "", side: "left", position: 30 / 75 },
          { id: "output", label: "", side: "right", position: 35 / 75 },
        ],
      },
      {
        id: C.pcSourceMux,
        label: "Mux",
        shape: "mux",
        x: 1380,
        y: 150,
        width: 50,
        height: 155,
        ports: [
          { id: "alu-result-input", label: "0", side: "left", position: 23 / 155 },
          { id: "alu-out-input", label: "1", side: "left", position: 78 / 155 },
          { id: "jump-input", label: "2", side: "left", position: 132 / 155 },
          { id: "output", label: "", side: "right", position: 78 / 155 },
          { id: "select", label: "", side: "top", position: 25 / 50 },
        ],
      },
    ],
    wires: [
      /* =====================================================
       * MEMORY ADDRESS AND DATA PATHS
       * ===================================================== */
      {
        id: W.pcToIorDMux,
        kind: "pc",
        from: port(C.pc, "output"),
        to: port(C.iorDMux, "pc-input"),
      },
      {
        id: W.iorDMuxToMemory,
        kind: "memory",
        from: port(C.iorDMux, "output"),
        to: port(C.memory, "address"),
      },
      {
        id: W.aluOutToIorDMux,
        kind: "memory",
        from: port(C.aluOutRegister, "output"),
        to: port(C.iorDMux, "alu-out-input"),
        route: [
          { x: 1345, y: 495 },
          { x: 1345, y: 920 },
          { x: 105, y: 920 },
          { x: 105, y: 490 },
        ],
      },
      {
        id: W.memoryToInstructionRegister,
        kind: "memory",
        labelAt: 0.45,
        from: port(C.memory, "data-output"),
        to: port(C.instructionRegister, "input"),
      },
      {
        id: W.memoryToMemoryDataRegister,
        kind: "memory",
        from: port(C.memory, "data-output"),
        to: port(C.memoryDataRegister, "input"),
        route: [
          { x: 385, y: 450 },
          { x: 385, y: 745 },
        ],
      },
      {
        id: W.bRegisterToMemory,
        kind: "memory",
        from: port(C.bRegister, "output"),
        to: port(C.memory, "write-data"),
        route: [
          { x: 965, y: 530 },
          { x: 965, y: 850 },
          { x: 195, y: 850 },
          { x: 195, y: 615 },
        ],
      },

      /* =====================================================
       * INSTRUCTION REGISTER FIELD ROUTES
       * ===================================================== */
      {
        id: W.instructionToControlUnit,
        kind: "data",
        label: "IR[31-26]",
        labelAt: 0.535,
        from: port(C.instructionRegister, "output"),
        to: port(C.controlUnit, "instruction"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 310 },
          { x: 700, y: 310 },
        ],
      },
      {
        id: W.instructionRsToRegisterFile,
        kind: "data",
        label: "IR[25-21]",
        labelAt: 0.45,
        from: port(C.instructionRegister, "output"),
        to: port(C.registerFile, "read-register-1"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 390 },
        ],
      },
      {
        id: W.instructionRtToRegisterFile,
        kind: "data",
        label: "IR[20-16]",
        labelAt: 0.35,
        from: port(C.instructionRegister, "output"),
        to: port(C.registerFile, "read-register-2"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 425 },
        ],
      },
      {
        id: W.instructionRtToRegDstMux,
        kind: "data",
        from: port(C.instructionRegister, "output"),
        to: port(C.regDstMux, "rt-input"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 425 },
          { x: 590, y: 425 },
          { x: 590, y: 490 },
        ],
      },
      {
        id: W.instructionRdToRegDstMux,
        kind: "data",
        label: "IR[15-11]",
        labelAt: 0.77,
        from: port(C.instructionRegister, "output"),
        to: port(C.regDstMux, "rd-input"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 540 },
        ],
      },
      {
        id: W.regDstMuxToRegisterFile,
        kind: "data",
        from: port(C.regDstMux, "output"),
        to: port(C.registerFile, "write-register"),
        route: [
          { x: 695, y: 515 },
          { x: 695, y: 500 },
        ],
      },
      {
        id: W.registerReadOneToARegister,
        kind: "data",
        from: port(C.registerFile, "read-data-1"),
        to: port(C.aRegister, "input"),
      },
      {
        id: W.registerReadTwoToBRegister,
        kind: "data",
        from: port(C.registerFile, "read-data-2"),
        to: port(C.bRegister, "input"),
      },
      {
        id: W.instructionImmediateToSignExtension,
        kind: "data",
        label: "IR[15-0]",
        labelAt: 0.70,
        from: port(C.instructionRegister, "output"),
        to: port(C.signExtension, "input"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 775 },
        ],
      },
      {
        id: W.instructionFunctToAluControl,
        kind: "data",
        label: "IR[5-0]",
        labelAt: 0.4425,
        from: port(C.instructionRegister, "output"),
        to: port(C.aluControl, "funct-input"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 890 },
          { x: 1075, y: 890 },
        ],
      },
      {
        id: W.instructionJumpToJumpShift,
        kind: "data",
        label: "IR[25-0]",
        labelAt: 0.22,
        from: port(C.instructionRegister, "output"),
        to: port(C.jumpShiftLeftTwo, "input"),
        route: [
          { x: 550, y: 450 },
          { x: 550, y: 345 },
          { x: 710, y: 345 },
          { x: 710, y: 320 },
          { x: 990, y: 320 },
          { x: 990, y: 280 },
        ],
      },

      /* =====================================================
       * REGISTER WRITE-BACK PATHS
       * ===================================================== */
      {
        id: W.memoryDataRegisterToMemToRegMux,
        kind: "memory",
        from: port(C.memoryDataRegister, "output"),
        to: port(C.memToRegMux, "mdr-input"),
        route: [
          { x: 575, y: 745 },
          { x: 575, y: 675 },
        ],
      },
      {
        id: W.aluOutToMemToRegMux,
        kind: "data",
        from: port(C.aluOutRegister, "output"),
        to: port(C.memToRegMux, "alu-out-input"),
        route: [
          { x: 1345, y: 495 },
          { x: 1345, y: 865 },
          { x: 610, y: 865 },
          { x: 610, y: 625 },
        ],
      },
      {
        id: W.memToRegMuxToRegisterFile,
        kind: "data",
        from: port(C.memToRegMux, "output"),
        to: port(C.registerFile, "write-data"),
        route: [
          { x: 700, y: 650 },
          { x: 700, y: 570 },
        ],
      },

      /* =====================================================
       * ALU INPUT AND OUTPUT PATHS
       * ===================================================== */
      {
        id: W.pcToAluSourceAMux,
        kind: "pc",
        from: port(C.pc, "output"),
        to: port(C.aluSourceAMux, "pc-input"),
        route: [
          { x: 95, y: 435 },
          { x: 95, y: 280 },
          { x: 975, y: 280 },
          { x: 975, y: 365 },
        ],
      },
      {
        id: W.aRegisterToAluSourceAMux,
        kind: "data",
        from: port(C.aRegister, "output"),
        to: port(C.aluSourceAMux, "a-input"),
      },
      {
        id: W.aluSourceAMuxToAlu,
        kind: "data",
        from: port(C.aluSourceAMux, "output"),
        to: port(C.alu, "source-a"),
        route: [
          { x: 1065, y: 390 },
          { x: 1065, y: 425 },
        ],
      },
      {
        id: W.bRegisterToAluSourceBMux,
        kind: "data",
        from: port(C.bRegister, "output"),
        to: port(C.aluSourceBMux, "b-input"),
      },
      {
        id: W.constantFourToAluSourceBMux,
        kind: "data",
        label: "4",
        from: point(973, 573),
        to: port(C.aluSourceBMux, "four-input"),
      },
      {
        id: W.signExtensionToAluSourceBMux,
        kind: "data",
        from: port(C.signExtension, "output"),
        to: port(C.aluSourceBMux, "immediate-input"),
        route: [
          { x: 855, y: 775 },
          { x: 855, y: 705 },
          { x: 935, y: 705 },
          { x: 935, y: 619 },
        ],
      },
      {
        id: W.signExtensionToBranchShift,
        kind: "branch",
        from: port(C.signExtension, "output"),
        to: port(C.branchShiftLeftTwo, "input"),
      },
      {
        id: W.branchShiftToAluSourceBMux,
        kind: "branch",
        from: port(C.branchShiftLeftTwo, "output"),
        to: port(C.aluSourceBMux, "shifted-input"),
        route: [
          { x: 980, y: 775 },
          { x: 980, y: 653 },
        ],
      },
      {
        id: W.aluSourceBMuxToAlu,
        kind: "data",
        from: port(C.aluSourceBMux, "output"),
        to: port(C.alu, "source-b"),
        route: [
          { x: 1065, y: 593 },
          { x: 1065, y: 520 },
        ],
      },
      {
        id: W.controlToAluControl,
        kind: "control",
        label: "ALUOp",
        labelAt: 0.1,
        from: port(C.controlUnit, "alu-op"),
        to: port(C.aluControl, "alu-op-input"),
        route: [
          { x: 1220, y: 115 },
          { x: 1220, y: 715 },
        ],
      },
      {
        id: W.aluControlToAlu,
        kind: "control",
        from: port(C.aluControl, "output"),
        to: port(C.alu, "control"),
        route: [
          { x: 1075, y: 650 },
          { x: 1150, y: 650 },
        ],
      },
      {
        id: W.aluToAluOutRegister,
        kind: "data",
        from: port(C.alu, "result"),
        to: port(C.aluOutRegister, "input"),
      },

      /* =====================================================
       * PC ENABLE AND NEXT-PC PATHS
       * ===================================================== */
      {
        id: W.aluZeroToBranchAndGate,
        kind: "control",
        from: port(C.alu, "zero"),
        to: port(C.branchAndGate, "zero-input"),
        route: [
          { x: 1235, y: 445 },
          { x: 1270, y: 445 },
          { x: 1270, y: 40 },
          { x: 350, y: 40 },
          { x: 350, y: 59 },
        ],
      },
      {
        id: W.controlPcWriteCondToBranchAndGate,
        kind: "control",
        label: "PCWriteCond",
        labelAt: 0.15,
        from: port(C.controlUnit, "pc-write-cond"),
        to: port(C.branchAndGate, "pc-write-cond-input"),
      },
      {
        id: W.branchAndGateToPcEnableGate,
        kind: "control",
        from: port(C.branchAndGate, "output"),
        to: port(C.pcEnableGate, "conditional-input"),
      },
      {
        id: W.controlPcWriteToPcEnableGate,
        kind: "control",
        label: "PCWrite",
        labelAt: 0.2,
        from: port(C.controlUnit, "pc-write"),
        to: port(C.pcEnableGate, "unconditional-input"),
      },
      {
        id: W.pcEnableGateToPc,
        kind: "control",
        from: port(C.pcEnableGate, "output"),
        to: port(C.pc, "enable"),
        route: [
          { x: 55, y: 93 },
          { x: 55, y: 400 },
        ],
      },
      {
        id: W.aluResultToPcSourceMux,
        kind: "pc",
        from: port(C.alu, "result"),
        to: port(C.pcSourceMux, "alu-result-input"),
        route: [
          { x: 1227, y: 495 },
          { x: 1227, y: 350 },
          { x: 1350, y: 350 },
          { x: 1350, y: 173 },
        ],
      },
      {
        id: W.aluOutToPcSourceMux,
        kind: "pc",
        from: port(C.aluOutRegister, "output"),
        to: port(C.pcSourceMux, "alu-out-input"),
        route: [
          { x: 1335, y: 495 },
          { x: 1335, y: 228 },
        ],
      },
      // Potential fix: instead of hardcoded space values,
      //    We can extend the label field (core/types.ts) to an array, then allow appending values (svgDatapathScene.ts)
      {
        id: W.jumpShiftToPcSourceMux,
        kind: "pc",
        label: "Jmp [27-0]\u00A0\u00A0\u00A0\u00A0\u00A0\u00A0Jmp [31-0]",
        labelAt: 0.40,
        from: port(C.jumpShiftLeftTwo, "output"),
        to: port(C.pcSourceMux, "jump-input"),
        route: [
          { x: 1340, y: 285 },
          { x: 1340, y: 282 },
        ],
      },
      {
        id: W.pcHighBitsToPcSourceMux,
        kind: "pc",
        label: "PC [31-28]",
        labelAt: 0.93,
        from: port(C.pc, "output"),
        to: point(1235, 282),
        route: [
          { x: 95, y: 435 },
          { x: 95, y: 280 },
          { x: 975, y: 280 },
          { x: 975, y: 235 },
          { x: 1235, y: 235 },
        ],
      },
      {
        id: W.pcSourceMuxToPc,
        kind: "pc",
        from: port(C.pcSourceMux, "output"),
        to: port(C.pc, "input"),
        route: [
          { x: 1490, y: 228 },
          { x: 1490, y: 25 },
          { x: 10, y: 25 },
          { x: 10, y: 500 },
        ],
      },

      /* =====================================================
       * CONTROL SIGNAL ROUTES
       * ===================================================== */
      {
        id: W.controlToIorDMux,
        kind: "control",
        label: "IorD",
        labelAt: 0.15,
        from: port(C.controlUnit, "ior-d"),
        to: port(C.iorDMux, "select"),
        route: [
          { x: 145, y: 137.5 },
          { x: 145, y: 300 },
        ],
      },
      {
        id: W.controlToMemoryRead,
        kind: "control",
        label: "MemRead",
        labelAt: 0.15,
        from: port(C.controlUnit, "memory-read"),
        to: port(C.memory, "memory-read"),
        route: [
          { x: 290, y: 159 },
          { x: 290, y: 320 },
        ],
      },
      {
        id: W.controlToMemoryWrite,
        kind: "control",
        label: "MemWrite",
        labelAt: 0.15,
        from: port(C.controlUnit, "memory-write"),
        to: port(C.memory, "memory-write"),
        route: [
          { x: 325, y: 186 },
          { x: 325, y: 320 },
        ],
      },
      {
        id: W.controlToInstructionRegisterWrite,
        kind: "control",
        label: "IRWrite",
        labelAt: 0.2,
        from: port(C.controlUnit, "ir-write"),
        to: port(C.instructionRegister, "write-enable"),
        route: [
          { x: 470, y: 235 },
        ],
      },
      {
        id: W.controlToRegDstMux,
        kind: "control",
        label: "RegDst",
        labelAt: 0.09,
        from: port(C.controlUnit, "reg-dst"),
        to: port(C.regDstMux, "select"),
        route: [
          { x: 775, y: 260 },
          { x: 775, y: 300 },
          { x: 720, y: 300 },
          { x: 680, y: 345 },
          { x: 640, y: 440 },
        ],
      },
      {
        id: W.controlToMemToRegMux,
        kind: "control",
        label: "MemToReg",
        labelAt: 0.10,
        from: port(C.controlUnit, "mem-to-reg"),
        to: port(C.memToRegMux, "select"),
        route: [
          { x: 395, y: 210 },
          { x: 395, y: 625 },
          { x: 580, y: 625 },
          { x: 580, y: 585 },
          { x: 655, y: 585 },
        ],
      },
      {
        id: W.controlToRegisterWrite,
        kind: "control",
        label: "RegWrite",
        labelAt: 0.25,
        from: port(C.controlUnit, "register-write"),
        to: port(C.registerFile, "register-write"),
        route: [
          { x: 845, y: 205 },
        ],
      },
      {
        id: W.controlToAluSourceAMux,
        kind: "control",
        label: "ALUSrcA",
        labelAt: 0.15,
        from: port(C.controlUnit, "alu-src-a"),
        to: port(C.aluSourceAMux, "select"),
        route: [
          { x: 1022, y: 145 },
          { x: 1022, y: 310 },
        ],
      },
      {
        id: W.controlToAluSourceBMux,
        kind: "control",
        label: "ALUSrcB",
        labelAt: 0.15,
        from: port(C.controlUnit, "alu-src-b"),
        to: port(C.aluSourceBMux, "select"),
        route: [
          { x: 965, y: 175 },
          { x: 965, y: 465 },
          { x: 1022, y: 465 },
        ],
      },
      {
        id: W.controlToPcSourceMux,
        kind: "control",
        label: "PCSource",
        labelAt: 0.15,
        from: port(C.controlUnit, "pc-source"),
        to: port(C.pcSourceMux, "select"),
        route: [
          { x: 1405, y: 83 },
          { x: 1405, y: 125 },
        ],
      },
    ],
  };

function port(
  componentId: MultiCycleComponentId,
  portId: string,
) {
  return { componentId, portId } as const;
}

function point(x: number, y: number) {
  return { point: { x, y } } as const;
}